---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u7010320/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R theme $DEPLOYPATH
